# Assignment — Pandas

20 exercises covering everything from Session 2: creating DataFrames, viewing/inspecting data, selecting/filtering, modifying data, missing data, and grouping/aggregation.

Write your code in the empty cell below each exercise, and run it to check your output before moving on. Remember to `import pandas as pd` at the top.

### Exercise 1 — Creating a DataFrame
Create a DataFrame from this dictionary: `{'Product': ['Pen', 'Notebook', 'Bag'], 'Price': [10, 25, 150], 'Stock': [100, 50, 20]}`. Print it.

In [1]:
import pandas as pd

# write your code here
dic = {'Product': ['Pen', 'Notebook', 'Bag'], 'Price': [10, 25, 150], 'Stock': [100, 50, 20]}

df = pd.DataFrame(dic)
print(df)

    Product  Price  Stock
0       Pen     10    100
1  Notebook     25     50
2       Bag    150     20

### Exercise 2 — head() with an argument
Using the DataFrame from Exercise 1, print only the first 2 rows using `head()`.

In [2]:
# write your code here
df.head(2)

    Product  Price  Stock
0       Pen     10    100
1  Notebook     25     50

### Exercise 3 — info()
Print the `.info()` summary of the DataFrame from Exercise 1.

In [3]:
# write your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  3 non-null      object
 1   Price    3 non-null      int64
 2   Stock    3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

### Exercise 4 — describe()
Print the `.describe()` statistical summary of the DataFrame from Exercise 1.

In [4]:
# write your code here
df.describe()

            Price       Stock
count    3.000000    3.000000
mean    61.666667   56.666667
std     76.865684   40.414519
min     10.000000   20.000000
25%     17.500000   35.000000
50%     25.000000   50.000000
75%     87.500000   75.000000
max    150.000000  100.000000

### Exercise 5 — Selecting a column and checking its type
Select the `Product` column from the DataFrame, print it, and print its type using `type()`.

In [5]:
# write your code here
print(df['Product'])
print(type(df['Product']))

0         Pen
1    Notebook
2         Bag
Name: Product, dtype: object
<class 'pandas.core.series.Series'>

### Exercise 6 — Filtering rows
Filter the DataFrame to show only products with `Price` greater than 20.

In [6]:
# write your code here
df[df['Price'] > 20]

    Product  Price  Stock
1  Notebook     25     50
2       Bag    150     20

### Exercise 7 — loc[] with rows and columns
Using `.loc[]`, select rows 0 through 1 and only the `Product` and `Stock` columns.

In [7]:
# write your code here
df.loc[0:1,['Product','Stock']]

    Product  Stock
0       Pen    100
1  Notebook     50

### Exercise 8 — Adding a calculated column
Add a new column `Total_Value` equal to `Price * Stock`. Print the updated DataFrame.

In [ ]:
# write your code here
df['Total_Value'] = df['Price'] * df['Stock']
df['Total_Value']

0    1000
1    1250
2    3000
Name: Total_Value, dtype: int64

### Exercise 9 — Updating an existing column
Subtract 5 from every value in the `Stock` column (simulating 5 units sold of each product). Print the result.

In [10]:
# write your code here
df['Stock'] = df['Stock'] - 5
df['Stock']

0    95
1    45
2    15
Name: Stock, dtype: int64

### Exercise 10 — Dropping a column
Drop the `Total_Value` column you created in Exercise 8. Print the result.

In [ ]:
# write your code here
print(df.drop(columns=['Total_Value']))

    Product  Price  Stock
0       Pen     10     95
1  Notebook     25     45
2       Bag    150     15

### Exercise 11 — Detecting missing values
Given `s = pd.Series([100, None, 300, None, 500])`, print which positions are missing using `.isnull()`.

In [15]:
s = pd.Series([100, None, 300, None, 500])
s.isnull()
# write your code here

0    False
1     True
2    False
3     True
4    False
dtype: bool

### Exercise 12 — Filling missing values with the mean
Fill the missing values in `s` from Exercise 11 with the Series' own mean (not a fixed number — use `s.mean()`).

In [16]:
# write your code here
s.mean()

300.0

### Exercise 13 — Grouping and summing
Given `df3 = pd.DataFrame({'Dept': ['Sales','Sales','IT','IT','IT'], 'Revenue':[1000,1500,2000,2500,1800]})`, group by `Dept` and print the **sum** of `Revenue` for each department (not the mean this time).

In [17]:
df3 = pd.DataFrame({'Dept': ['Sales', 'Sales', 'IT', 'IT', 'IT'], 'Revenue': [1000, 1500, 2000, 2500, 1800]})

# write your code here
df3.groupby('Dept')['Revenue'].sum()

Dept
IT       6300
Sales    2500
Name: Revenue, dtype: int64

### Exercise 14 — apply() with a custom function
Given `df4 = pd.DataFrame({'Price':[100,200,300]})`, write a function `apply_discount(price)` that returns 90% of the price, and use `.apply()` to create a new `Discounted` column.

In [22]:
df4 = pd.DataFrame({'Price': [100, 200, 300]})

# write your code here
def apply_discount(price):
    return price * 0.9

df4 = pd.DataFrame({'Price':[100,200,300]})
df4['Discounted'] = df4['Price'].apply(apply_discount)
df4

   Price  Discounted
0    100        90.0
1    200       180.0
2    300       270.0

### Exercise 15 — Sorting
Given `df5 = pd.DataFrame({'Name':['Ali','Sara','Omar'],'Score':[88,95,72]})`, sort by `Score` in descending order.

In [23]:
df5 = pd.DataFrame({'Name': ['Ali', 'Sara', 'Omar'], 'Score': [88, 95, 72]})

# write your code here
df5.sort_values(by='Score',ascending=False)
print(df5)

   Name  Score
0   Ali     88
1  Sara     95
2  Omar     72

### Exercise 16 — value_counts()
Given `pd.Series(['A','B','A','C','B','A'])`, print how many times each value appears using `.value_counts()`.

In [24]:
# write your code here
df16 = pd.Series(['A','B','A','C','B','A'])
df16.value_counts()

A    3
B    2
C    1
Name: count, dtype: int64

### Exercise 17 — Duplicates
Given `df6 = pd.DataFrame({'A':[1,2,2,3,3,3]})`, print which rows are duplicates using `.duplicated()`, then print the DataFrame with duplicates removed using `.drop_duplicates()`.

In [28]:
df6 = pd.DataFrame({'A': [1, 2, 2, 3, 3, 3]})

# write your code here
print(df6.duplicated())
print(df6.drop_duplicates())

0    False
1    False
2     True
3    False
4     True
5     True
dtype: bool
   A
0  1
1  2
3  3

### Exercise 18 — Group by and average
Given `df7 = pd.DataFrame({'Category':['Electronics','Clothing','Electronics'], 'Sales':[500,300,700]})`, group by `Category` and print the average `Sales` for each.

In [29]:
df7 = pd.DataFrame({'Category': ['Electronics', 'Clothing', 'Electronics'], 'Sales': [500, 300, 700]})

# write your code here
df7.groupby('Category')['Sales'].mean()

Category
Clothing       300.0
Electronics    600.0
Name: Sales, dtype: float64

### Exercise 19 — Working with dates
Given `df8 = pd.DataFrame({'Date': ['2023-01-15','2023-06-20','2024-02-10']})`, convert the `Date` column to a real datetime type, then filter to show only dates after `'2023-05-01'`.

In [32]:
df8 = pd.DataFrame({'Date': ['2023-01-15', '2023-06-20', '2024-02-10']})

# write your code here
df8['Date'] = pd.to_datetime(df8['Date'])

df8[df8['Date'] > '2023-05-01']

        Date
1 2023-06-20
2 2024-02-10

### Exercise 20 — Comprehensive: save and reload
Given `df9 = pd.DataFrame({'Name':['Ali','Sara'], 'Age':[25,30]})`, save it to a CSV file called `test_output.csv` (without the index column), then read that same file back into a new DataFrame and print it.

In [33]:
df9 = pd.DataFrame({'Name': ['Ali', 'Sara'], 'Age': [25, 30]})

# write your code here
df9.to_csv('test_output.csv',index=False)

new_csv = pd.read_csv('test_output.csv')
print(new_csv)

   Name  Age
0   Ali   25
1  Sara   30

---
### Done! 🎉
Double check your outputs, then send this notebook back — you'll get the fully solved version afterward.